### ISSUE TITLE
ssh permission denied

### ISSUE THREAD

**Issue by keller** [johanan/Dockerized-Wordpress-the-Correct-way#1]
Thanks for putting this together. I'm trying to learn more about ansible and docker and I like how you've set this up. I'm having an issue though running development_build.sh. 

I get a "SSH Error: Permission denied (publickey)." when it runs `ansible-playbook  ... ../ansible/new_wordpress_setup.yml` everything appears to be working fine before that. It appears to be trying to ssh to the vagrantbox using the vagrant user and vagrant key in the .vagrant directory but that no longer works. The new user ansible set up works with my ssh key. I'm not really sure what is suppose to be happening. I'll attach my output, append -vvvv to the ansible-playbook command to get some more output.

Thanks for your help.

**Comment by keller** [comment]
$  ./development_build.sh dev.kateraedavis.com 4.3.1
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vagrant_default_1450651979366_38442
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.34
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /vagrant => /Users/kellerdavis/testblog/vagrant
    default: /var/www/html => /Users/kellerdavis/testblog/vagrant/vmwordpress
==> default: Running provisioner: ansible...

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [basic_server_setup | Install ufw] ************************************** 
ok: [default]

TASK: [basic_server_setup | create a new user] ******************************** 
changed: [default]

TASK: [basic_server_setup | authorized_key user="{{ newuser }}" key="{{ lookup('file', ssh_key ) }}"] *** 
changed: [default]

TASK: [basic_server_setup | Make sure we can sudo] **************************** 
changed: [default]

TASK: [basic_server_setup | Configure ufw] ************************************ 
ok: [default]

TASK: [basic_server_setup | Default deny] ************************************* 
changed: [default]

TASK: [basic_server_setup | Disable root SSH] ********************************* 
changed: [default]

TASK: [basic_server_setup | Restart SSH] ************************************** 
changed: [default]

PLAY RECAP ******************************************************************** 
default                    : ok=9    changed=6    unreachable=0    failed=0   


PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: testblog
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/kellerdavis/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/kellerdavis/testblog/vagrant/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=testblog -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450652018.7-260488708868251 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1450652018.7-260488708868251 && echo $HOME/.ansible/tmp/ansible-tmp-1450652018.7-260488708868251'
fatal: [default] => SSH Error: Permission denied (publickey).
    while connecting to 127.0.0.1:2222
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [docker | Add repo from Docker] ***************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/kellerdavis/new_wordpress_setup.retry

default                    : ok=0    changed=0    unreachable=1    failed=0   

Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
$ ssh -p2222 testblog@dev.kateraedavis.com
The authenticity of host '[dev.kateraedavis.com]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:RlWWAIuj+rrNYHcHxMeCO/w/eg1ozlOkMIGInAeBJs8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[dev.kateraedavis.com]:2222' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Sun Dec 20 22:54:16 UTC 2015

  System load:  0.58              Processes:           83
  Usage of /:   3.4% of 39.34GB   Users logged in:     0
  Memory usage: 26%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Sun Dec 20 22:54:17 2015 from 10.0.2.2
testblog@vagrant-ubuntu-trusty-64:~$ exit
logout
Connection to dev.kateraedavis.com closed.
$

**Comment by keller** [comment]
Upgrading Vagrant fixed everything for me. Thanks.

**Comment by johanan** [comment]
Thank you for updating this. When you first opened the issue I tried replicating the issue, but was not able to.
