### ISSUE TITLE
OS X El Capitan support

### ISSUE THREAD

**Issue by elmcrest** [johanan/Dockerized-Wordpress-the-Correct-way#2]
Hey Joshua,

first of all thx for this repository, it feels like this could really help us :)

Anyways, can you confirm the OS X El Capitan Support?

I ran into the following when trying to set things up with `./development_build.sh my.domain.com 4.4.2`:

```
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 81
Could not request local forwarding.
```

I have to mention though, that I already installed the "vanilla" Docker Setup for OS X - so there are probably two virtualbox instances which might conflict.

And a question in general - it seems it's intended to change the /etc/hosts file to decide where the setup goes and comes from. Is this correct? And if yes, wouldn't it make sense to add this to the script(s) too and have a --local flag or something?

Thx,
Marius

**Comment by elmcrest** [comment]
ok meanwhile I tried it again with uninstalling vanilla docker and reinstalling vagrant - though no success.
at least I could get rid of the error message but now after:

```
....
TASK: [bring it all up] ******************************************************* 
changed: [default]

TASK: [Clean all unused images] *********************************************** 
changed: [default]

TASK: [Set permissions in container] ****************************************** 
changed: [default]

PLAY RECAP ******************************************************************** 
default                    : ok=67   changed=29   unreachable=0    failed=0   

Password:
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
```

the site isn't loaded, like Chrome just reaches the server.

Vagrant is Version 1.8.1
ansible is as in requirements.txt (without a env)

**Comment by johanan** [comment]
Marius

I have OS X El Capitan (10.11.13). My vagrant was a little behind, but I am going to update it and see if I can replicate the issue.

**Comment by johanan** [comment]
Marius

I was just able to build and load the project. I have a few questions. Did you create an .env file with all the values? It should be very similar to the example_env file. Next did you enter your user credentials when development_build.sh asked for them? It uses sudo which is needed on OS X to forward the port to 80.

Josh

**Comment by elmcrest** [comment]
Hey again,

to resolve this: to my shame I didn't realise I'd need to rename the example_env into something the script can actually find ... so any env -> .env

with that it now went smooth until I just could login :) really nice :+1:

So this could be closed. Though a little reminder to my other question:

It seems it's intended to change the /etc/hosts file to decide where the setup goes and comes from. Is this correct? And if yes, wouldn't it make sense to add this to the script(s) too and have a --local flag or something?

Thx,
Marius

**Comment by johanan** [comment]
Marius

I need to create a README that makes the env file creation more clear.

You are correct that the hosts file should be changed to run a site locally with a full DNS name. I haven't done much with modifying the hosts from a script. I will take a look and see what I can do.

Josh
